apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Herda tudo da base
resources:
  - ../../base

# Patches para o ambiente de PROD
patches:
  # Prod começa com 2 réplicas
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coacha-deploy
        namespace: coacha-app
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: coacha
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "100m"
                  limits:
                    memory: "512Mi"
                    cpu: "1000m"

  # Prod com valores de produção no ConfigMap
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coacha-config
        namespace: coacha-app
      data:
        APP_ENV: "production"
        APP_GREETING: "Olá do ArgoCD! GitOps funcionando! 🚀"
        MAX_STUDENTS: "200"
